version: "3"
services:
  apisix:
    image: apache/apisix:3.1.0-debian
    volumes:
      - ./apisix/config.yml:/usr/local/apisix/conf/config.yml:ro
      - ./apisix/apisix.yml:/usr/local/apisix/conf/apisix.yml:ro
      - ./openapi.yaml:/usr/local/apisix/conf/openapi.yaml:ro
      - ./custom-plugins:/opt/apisix/plugins:ro
    ports:
      - "9080:9080"
    environment:
      - GATEWAY_PORT=9080