openapi: 3.0.1
info:
  title: Conference Plugin
  description: A plugin that allows the retrieve speaker's sessions.
  version: 'v1'
servers:
  - url: http://localhost:9080
paths:
  /speaker/{id}/sessions:
    get:
      operationId: GetSpeakerSessions
      parameters:
        - name: id
          in: path
          description: Format - int32.
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content: {}